### ISSUE TITLE
Cardboard Fails to use Calibrated Profile (Object is null when calling method setVRModeEnabled)

### ISSUE THREAD

**Issue by jules43** [googlevr/gvr-unity-sdk#751]
I am having problems with my Unity based cardboard application failing to initialise the profile correctly and then not displaying the settings icon and not using the calibrated headset viewer/screen.

I have created an empty project and then imported GoogleVRForUnity_1.40.0.unitypackage and subsequently GVRBackwardsCompatibility.unitypackage. I then opened the scene Assets\Demos\Scenes\GVRDemo, setup the bundle identifier and deployed to a Samsung S7

When I build and run the app on the S7, I see the following in logcat:

```
10-17 10:19:11.537 29083 29100 E Unity   : Exception creating object com.google.vr.platform.unity.UnityVrActivityListener: UnityEngine.AndroidJavaException: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
10-17 10:19:11.537 29083 29100 E Unity   : java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
10-17 10:19:11.537 29083 29100 E Unity   :      at android.os.Handler.<init>(Handler.java:200)
10-17 10:19:11.537 29083 29100 E Unity   :      at android.os.Handler.<init>(Handler.java:114)
10-17 10:19:11.537 29083 29100 E Unity   :      at android.app.Dialog.<init>(Dialog.java:152)
10-17 10:19:11.537 29083 29100 E Unity   :      at android.app.AlertDialog.<init>(AlertDialog.java:200)
10-17 10:19:11.537 29083 29100 E Unity   :      at android.app.AlertDialog$Builder.create(AlertDialog.java:1103)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.showWarningDialog(AndroidNCompat.java:324)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.handleVrCoreAbsence(AndroidNCompat.java:298)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.setVrModeEnabled(AndroidNCompat.java:113)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.setVrModeEnabled(AndroidNCompat.java:76)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.ndk.base.AndroidCompat.setVrModeEnabled(AndroidCompat.java:32)
10-17 10:19:11.537 29083 29100 E Unity   :      at com.google.vr.p
10-17 10:19:11.549 29083 29100 E Unity   : Object is null when calling method setVRModeEnabled
10-17 10:19:11.549 29083 29100 E Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
10-17 10:19:11.549 29083 29100 E Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
10-17 10:19:11.549 29083 29100 E Unity   : UnityEngine.Logger:Log(LogType, Object)
10-17 10:19:11.549 29083 29100 E Unity   : UnityEngine.Debug:LogError(Object)
10-17 10:19:11.549 29083 29100 E Unity   : Gvr.Internal.BaseAndroidDevice:CallObjectMethod(AndroidJavaObject, String, Object[]) (at E:\Dev\CardTest\Assets\GoogleVR\Legacy\Scripts\Internal\VRDevices\BaseAndroidDevice.cs:76)
10-17 10:19:11.549 29083 29100 E Unity   : Gvr.Internal.AndroidDevice:SetVRModeEnabled(Boolean) (at E:\Dev\CardTest\Assets\GoogleVR\Legacy\Scripts\Internal\VRDevices\AndroidDevice.cs:40)
10-17 10:19:11.549 29083 29100 E Unity   : GvrViewer:InitDevice() (at E:\Dev\CardTest\Assets\GoogleVR\Scripts\GvrViewer.cs:388)
10-17 10:19:11.549 29083 29100 E Unity   : GvrViewer:Awake() (at E:\Dev\CardTest\Assets\GoogleVR\Scripts\GvrViewer.cs:412)
```
The result is that the demo runs but the configuration of the distortion etc does not match the headset / phone.

If I run the Cardboard app the demos do match the configured headset as does another random Cardboard app I tested.

This replicates a problem I am having with an app I have in the store which I am trying to fix. I can't upgrade to a newer version of Unity.

Suggestions please?

Thanks

Unity: 5.3.8p2
Google VR for Unity: 1.40.0
Cardboard: 1,8
Google VR Services: 1.10.170928015
Phone: Samsung Galaxy S7
Model: SM-G930F
Android Version: 7.0  Patch 1/8/17

**Comment by jules43** [comment]
Having looked for similar problems reported previously I note that my Android Manifest file is exactly a copy of AndroidManifest-Cardboard.xml which comes with the Unity plugin.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application android:icon="@drawable/app_icon"
                 android:label="@string/app_name">
        <activity android:name="com.google.unity.GoogleUnityActivity"
                  android:label="@string/app_name"
                  android:screenOrientation="landscape"
                  android:launchMode="singleTask"
                  android:configChanges="mcc|mnc|locale|touchscreen|keyboard|keyboardHidden|navigation|orientation|screenLayout|uiMode|screenSize|smallestScreenSize|fontScale">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="com.google.intent.category.CARDBOARD" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>
        <meta-data android:name="IMMERSIVE_MODE" android:value="true" />
    </application>
```
The activity is com.google.unity.GoogleUnityActivity.

I also note that the app successfully picks up calibration profile on a Motorola G4 Plus.

Thanks

Jules

**Comment by googlevr-unreal** [comment]
Can you try comment out the line
`device.SetVRModeEnabled(vrModeEnabled);`
in GvrViewer.cs and see if it fixes the issue? I think you don't need to call that method for cardboard app.

**Comment by bopangzz** [comment]
Can you try comment out the following line in GvrViewer.cs and see if it fixes your issue?
` device.SetVRModeEnabled(vrModeEnabled);`
Note that there are two of them.

**Comment by jules43** [comment]
In my GvrViewer.cs that is line 355. I commented it out and rebuilt/deployed. The visual effect seemed to be the same, ie cross-eyed mode when using my Homido mini.

The log comes out a little differently, the relevant bit appears to be here:
```
10-17 19:39:36.702 20217 20255 E Unity   : Exception creating object com.google.vr.platform.unity.UnityVrActivityListener: UnityEngine.AndroidJavaException: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
10-17 19:39:36.702 20217 20255 E Unity   : java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
10-17 19:39:36.702 20217 20255 E Unity   :      at android.os.Handler.<init>(Handler.java:200)
10-17 19:39:36.702 20217 20255 E Unity   :      at android.os.Handler.<init>(Handler.java:114)
10-17 19:39:36.702 20217 20255 E Unity   :      at android.app.Dialog.<init>(Dialog.java:152)
10-17 19:39:36.702 20217 20255 E Unity   :      at android.app.AlertDialog.<init>(AlertDialog.java:200)
10-17 19:39:36.702 20217 20255 E Unity   :      at android.app.AlertDialog$Builder.create(AlertDialog.java:1103)
10-17 19:39:36.702 20217 20255 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.showWarningDialog(AndroidNCompat.java:357)
10-17 19:39:36.702 20217 20255 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.handleVrCoreAbsence(AndroidNCompat.java:314)
10-17 19:39:36.702 20217 20255 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.setVrModeEnabled(AndroidNCompat.java:121)
10-17 19:39:36.702 20217 20255 E Unity   :      at com.google.vr.cardboard.AndroidNCompat.setVrModeEnabled(AndroidNCompat.java:72)
10-17 19:39:36.702 20217 20255 E Unity   :      at com.google.vr.platform.unity.UnityVrActivityListener.<init>(UnityVrActivityListener.java:95)
10-17 19:39:36.702 20217 20255 E Unity   :      at
10-17 19:39:36.755 20217 20255 E Unity   : Object is null when calling method onPause
10-17 19:39:36.755 20217 20255 E Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
10-17 19:39:36.755 20217 20255 E Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
10-17 19:39:36.755 20217 20255 E Unity   : UnityEngine.Logger:Log(LogType, Object)
10-17 19:39:36.755 20217 20255 E Unity   : UnityEngine.Debug:LogError(Object)
10-17 19:39:36.755 20217 20255 E Unity   : Gvr.Internal.BaseAndroidDevice:CallObjectMethod(AndroidJavaObject, String, Object[]) (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\VRDevices\BaseAndroidDevice.cs:76)
10-17 19:39:36.755 20217 20255 E Unity   : Gvr.Internal.AndroidDevice:OnPause(Boolean) (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\VRDevices\AndroidDevice.cs:49)
10-17 19:39:36.755 20217 20255 E Unity   : GvrViewer:OnEnable() (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\GvrViewer.cs:503)
```
I note that I am starting my app in magic window mode and then switching. You can see the actual switch breaking here:
```
10-17 19:39:39.306 20217 20255 E Unity   : Object is null when calling method setVRModeEnabled
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.Logger:Log(LogType, Object)
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.Debug:LogError(Object)
10-17 19:39:39.306 20217 20255 E Unity   : Gvr.Internal.BaseAndroidDevice:CallObjectMethod(AndroidJavaObject, String, Object[]) (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\VRDevices\BaseAndroidDevice.cs:76)
10-17 19:39:39.306 20217 20255 E Unity   : Gvr.Internal.AndroidDevice:SetVRModeEnabled(Boolean) (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\VRDevices\AndroidDevice.cs:40)
10-17 19:39:39.306 20217 20255 E Unity   : GvrViewer:set_VRModeEnabled(Boolean) (at E:\Dev\UbietyVR\Assets\GoogleVR\Scripts\GvrViewer.cs:91)
10-17 19:39:39.306 20217 20255 E Unity   : ubiety.vr.VRPlayer:set_VRMode(Boolean) (at E:\Dev\UbietyVR\Assets\Scripts\VRPlayer\VRPlayer.cs:192)
10-17 19:39:39.306 20217 20255 E Unity   : ubiety.vr.GUIScreenButton:CardSwitch() (at E:\Dev\UbietyVR\Assets\Scripts\GUI\ScreenSpace\GUIScreenButton.cs:19)
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.Component:SendMessage(String, Object, SendMessageOptions)
10-17 19:39:39.306 20217 20255 E Unity   : UnityEngine.Component:SendMessage(String) (at /Users/builduser/buildslave/unity/buil
10-17 19:39:42.334 20217 20217 I Unity   : windowFocusChanged: false
10-17 19:39:42.336 20217 20217 I Unity   : onPause
10-17 19:39:42.369 20217 20255 E Unity   : Object is null when calling method onPause
```

**Comment by bopangzz** [comment]
Sorry I missed that. Can you try comment out line 40 in AndroidDevice.cs? Basically make the SetVRModeEnabled function a no-op. 

Though the error you saw in the logcat may not be the the cause of the visual effect you saw. Can you also attach a screenshot? Have you tried pair with other viewer? Is the distortion correct for other viewers?

**Comment by jules43** [comment]
My assumption is that somehow it gets the wrong profile data in (UpdateScreenData). It's notable that the settings icon doesn't get drawn either. 

Here are three screen shots, all taken with Homido Mini configured:
https://drive.google.com/drive/folders/0B0HJORhfMvneT3NQVVcyQmlqd0k?usp=sharing

CardboardDemo is a shot from the actual Cardboard app.
MagicVR is a shot from a Cardboard app playing a video.
MyApp is a shot from my app.

Note in particular the placement of the cursor dots in CardboardDemo and MyApp. The cursor is a 3D object straight in front of the middle camera. When my app is working (on other phones) the cursor looks 3D and with Homido Mini appears about the same place as the CardboardDemo one.

I note that the app works as expected on a Motorola Moto G4 Plus and an S7 Edge (with same OS, GoogleVR services, Cardboard and Unity).

Commenting out line 40 of AndroidDevice.cs made no difference to the appearance.

I put a breakpoint in AndroidDevice.Init() and stepped through the code. Line 35 of AndroidDevice.cs does activityListener = Create(ActivityListenerClass). And that call fails returning null.

Everything else in InitDevice seems sensible.

Finally I have to apologise, I've done my last set of tests with my full app, rather than the 1.40 GVRDemo. I've re-run the tests and get the same results, and I've added an additional screenshot from GVRDemo.

I've also added the full adb logcat -s Unity from the demo app to GVRDemoLogcat.txt and put in on the Google drive too.

This is probably a red herring, but I'd expect the settings icon, the separator bar and the back button to all be drawn as they are in the Cardboard demo. However on my S7 neither the GVRDemo nor my own app display either of these and as SupportsNativeUILayer is hardcoded to true for Android I'm assuming this is also supposed to be done in the Google VR Services? On the S7 Edge we do get a settings button with my own app.

Hope that some of this helps. Please let me know if there's anything else I can do.

**Comment by bopangzz** [comment]
Thanks for the all the information. They are pretty helpful. Just one thing to confirm here, the setting button and your app works as expected on Moto G4n and S7 Edge but with the same build you are having those issue on S7? What is the Android Version for you G4 and S7 Edge?

**Comment by jules43** [comment]
Situation is not as straight forward as one might hope.

**Moto G4+**
OS: Android 7.0 August Patch
Google VR Services: Not installed
Cardboard App: 1.8
My app - draws the settings / separator / back and seems to have correct profile
GVRDemo - doesn't draw settings etc but does have correct profile

I retested the two apps a couple of times and definitely what's happening.

I installed GoogleVR servives and nothing changed.

**Samsung Galaxy S7 Edge**
OS: Android 7.0 August Patch
Google VR services: 1.10.170928015
Cardboard App: 1.8
My app - recent but not same build (same GVR/Unity), does draw settings and does do correct profile
GVRDemo - untested

I note that my app (as opposed to GVRDemo) is running an older version of the Google VR Unity plugin.

As a final test I used the settings icon in my app on the S7 to change the profile (it prompted for VR Services or Cardboard - I chose Cardboard) and changed the config and went back to app and saw it change.

I may be able to get someone to try GVRDemo on the Edge tomorrow, for now I'm signing off until midday UK time.

**Comment by jules43** [comment]
Just re-run all the tests with the same builds (SetVRModeEnabled commented out):

S7
My App            Icon: No  Profile: No
GVRDemo        Icon: No  Profile: No

(Profile used for both builds is the same, just doesn't match the Cardboard configured one).

S7 Edge
My App            Icon: No   Profile: Yes
GVRDemo        Icon: No  Profile: Yes

Moto G4+
My App           Icon: Yes   Profile: Yes
GVRDemo       Icon: No   Profile: Yes

All: Android 7 August, Card 1.8, GVR Services: 1.10.17..., Unity 5.3.8p2

Doesn't seem to matter if GVR Services are installed or not.

My App older version of GoogleVR plugin. GVRDemo 1.40 version of GoogleVR plugin.

Icon means drawing settings icon, back button, separator.
Profile means reacts to changes in profile within Cardboard app.

**Comment by bopangzz** [comment]
Hi, 

I think there are basically two issue here and they may not be related.
1. The setting icon is missing.
2. The distortion is not correct on S7(It looks like this issue: #421)

For the icon issue, I tried to build GVRDemo with Unity 5.3.8p2 and GVR Unity SDK1.40 and run it on my Nexus 5, the icon shows up fine. Can you share your build of GVRDemo with Unity 5.3.8p2 and GVR Unity SDK 1.40 so I can test on my phone?

For the S7 distortion issue, according to #421, it should be fixed with GVR Services 1.10.17... Can you try revert your changes(make it call SetVRModeEnabled) with Google VR Services installed and see if you have the correct distortion? SetVRModeEnabled shouldn't throw the previous exception if you have GoogleVR Services installed. 

And could you also try set your screen resolution to native on you S7 and see if you still have the distortion issue? This is just to check if you are having the same issue as #421.

**Comment by jules43** [comment]
**Regarding 1: Setting Icon Missing**

I've placed a fresh build of the GVRDemo scene using Unity 5.3.8p2 and plugin 1.40  into the same drive folder (https://drive.google.com/drive/folders/0B0HJORhfMvneT3NQVVcyQmlqd0k?usp=sharing) and called it GVRDemoAndroidDbg.apk.

I've tested it on my S7 with latest GVR Services installed in FHD and WQHD res and the settings icon doesn't show up.

I've also uploaded a copy of my own app (ubeityvrpriorsfieldcarddbg.apk). It starts in magic window mode, touch screen to bring up switch icon in bottom right corner, then switch to VR mode. I've run this build on S7 (no settings icon) and Moto G4+ (settings icon appears). As mentioned before we tested a similar build on S7 Edge and it also had settings icon appear.

This app is running quite a lot older version of the plugin.

**Regarding 2: Incorrect distortion #421** 

Turning off power saving mode and raising the resolution from FHD to WQHD does fix the distortion problem. with both my app and GVRDemo.

Installing Google VR Services (1.10.170928015) which appears to be the build that is intended to solve the problem - cleared the pairing with the Homido. Once I'd reset it then that continued to work fine in WQHD.

With 1.10.17... installed switching back to FHD still has the same problem in both. Comments in the #421 thread would indicate this might be common to earlier Unity / Plugin combinations.

**Comment by jules43** [comment]
I have added some comments to #421 but I note that that issue is marked as closed, despite that it is apparently not fixed for some combinations of Unity / Plugin.

**Comment by jules43** [comment]
Moving to 2017 is definitely desirable, however for current purposes there are three main motivations for staying with 5.3:

1. I am fixing bugs in a already released product and upgrading to 5.6 or 2017 would likely introduce a larger number of unknown bugs which would require heavier testing to fix.

2. I am also dealing with bugs in a second product which is close to release and too close to release to go through a major upgrade.

3. Finally, someone in my team made an attempt to upgrade to 5.6 previously and hit a bunch of compatibility issues around VR (Cardboard, Gear and Oculus) which they did not manage to fix in the time allocated for the experiment. So presumption is that the upgrade is non-trivial, and we have yet to find the time for it.

**Comment by bopangzz** [comment]
I tried your test app on a Nexus 5 and S7 edge and I can't reproduce the missing icon issue. I will try to find a S7 and run some test. But in the meanwhile, can you send me a full logcat running your GVRDemo build on S7 without "Unity" filter?

**Comment by jules43** [comment]
I've placed the logcat in the same Google Drive directory. This is a direct link: https://drive.google.com/open?id=0B0HJORhfMvneU1BFb2NDcGEwOGc

**Comment by fredsa** [comment]
@jules43 Both issues you mentioned (appearance of settings gear icon and correct distortion) have been fixed.

Here's the configuration I tested:
* Samsung S7 Edge (Model SM-G935V)
* Android 7.0 (Android N)
* Settings > Display > Resolution > FHD
* Unity 5.6.4p1
* Google VR SDK 1.100.1
* Google VR Services 1.10.170928015

**Comment by fredsa** [comment]
@jules43 Since everything is working with the latest SDK and most recent Unity 5.6 release, I recommend updating your project to use these or later versions of Unity and the Google VR SDK for Unity.

I understand your concerns about updating your tools at this stage in your projects. However, I think you'll likely find that the latest Unity 5.6 release has fewer migration issues than perhaps one of the earlier 5.6 releases.

**Comment by jules43** [comment]
Thanks for investigating and for your feedback.
