### ISSUE TITLE
Unable to cast audio to TV via Chromecast monoscopic view

### ISSUE THREAD

**Issue by imbible** [googlevr/gvr-unity-sdk#803]
Audio casting does not work on monoscopic view when casting to TV via Chromecast. 

Found using:
 * Google VR SDK version: 1.110
 * Unity version: 2017.2.0f3
 * Phone manufacturer, model, and O/S version: Google Pixel
 * Viewer manufacturer & model: Google Daydream

Steps to reproduce the issue:
 1. Build the video demo app of google VR SDK to the Google Pixel. The path of the scene is Assets/GoogleVR/Demos/Scenes/VideoDemo from Unity.
 2. Launch Google daydream app from Pixel, put the phone into the daydream headset.
 3. Use the controller to press the Cast button, select the available chromecast. Make sure you also press the Cast Audio toggle-bar to enable audio casting.
 4. Launch the video demo app. It shows "Google VR service - Audio casting not supported for this app". The audio comes from the phone rather than from the TV.

Workarounds:
N/A

Additional comments:
 1. On step 4, if you launch youtube VR app, it casts the audio to TV without the error message. Maybe I'm wrong but it seems that only the apps made by google can cast audio to TV in monoscopic view.

**Comment by rusmaxham** [comment]
Thanks for the report.  We'll take a look.

**Comment by rusmaxham** [comment]
This is a known issue that is being worked on at the platform level.

**Comment by imbible** [comment]
@rusmaxham Any progress?

**Comment by imbible** [comment]
@rusmaxham Any progress?

**Comment by rusmaxham** [comment]
This should be fixed on the Lenovo Mirage Solo devices, but will have to wait for Android P to come to smartphone Daydream devices.

**Comment by imbible** [comment]
@chaosemer Why is this closed?

**Comment by imbible** [comment]
@chaosemer Why is this closed?

**Comment by imbible** [comment]
@rusmaxham @chaosemer It is still reproducible in Android P. Why is this closed?

**Comment by chaosemer** [comment]
Thanks for the nagging. With Android P out, I thought this was fixed. Will reinvestigate.

**Comment by rusmaxham** [comment]
We were unable to get this fix into Android P.  Casting with audio from Unity VR apps, for now, is only supported on the Mirage Solo.

**Comment by imbible** [comment]
Now that you were unable to get this fix into Android P, it is still a reproductible bug. Right? Why did you close it?
@rusmaxham @chaosemer
